import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/app/_newCompoents/Navbar";
import { auth } from "@/auth";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const user = await auth();
  if (!user) return null;
  if (user.user.role !== "FORMATEUR") {
    redirect("/login");
  }

  return (
    <div className="h-screen flex overflow-hidden ">
      <Navbar />
      <div className="w-screen  bg-gray-50">{children}</div>
    </div>
  );
};
export default RootLayout;
